### ISSUE TITLE
timeout in secs as opposed to ms

### ISSUE THREAD

**Issue by samuelgoto** [samuelgoto/idle-detection#11]
was just watching the CDS livestream and ran into this :)

@6h39  on the CDS talk :)

https://www.youtube.com/watch?v=7ohLjc9-FT4

@surma thanks for the feedback :)

PS also, how in the world did idle detection win over the contacts picker API ? :)

**Comment by surma** [comment]
🎉 cc @jakearchibald

> PS also, how in the world did idle detection win over the contacts picker API ? :)

No clue 😂

**Comment by reillyeon** [comment]
Is milliseconds a strong preference? Idle thresholds are not supposed to be fine grained. The benefit would be consistency with the rest of the web platform which seems to prefer milliseconds.

**Comment by domenic** [comment]
https://w3ctag.github.io/design-principles/#milliseconds
