### ISSUE TITLE
Privacy section: Exposing that the user is active may be undesirable

### ISSUE THREAD

**Issue by birtles** [samuelgoto/idle-detection#15]
One of the use cases listed is a chat application that show's the users online status.

I suggest the privacy section might want to discuss whether this is desirable or not. A user may deliberately avoid opening a chat application until they are ready to interact with a particular acquaintance. I think most users would assume that their acquaintance sees them as offline until that they open the app again (I believe this is how Messenger works). If their online status is revealed they may feel their privacy has been undermined and it could be awkward or even become a vector for stalking.

**Comment by reillyeon** [comment]
This API is not available in Service Workers and so cannot be used to determine whether the user is idle unless the application is open.
