### ISSUE TITLE
Is "locked" redundant with page visibility?

### ISSUE THREAD

**Issue by inexorabletash** [samuelgoto/idle-detection#4]
Especially on mobile, there are existing events when the page is no longer visible. Is that equivalent to the "locked" state ?

cc: @reillyg

**Comment by reillyeon** [comment]
The "locked" state allows a site to differentiate between their page being in the background and therefore not visible vs. the screen actually being locked, indicating the user is not present.

**Comment by reillyeon** [comment]
Re-open if you disagree with my previous comment.
